### ISSUE TITLE
Create Trias GAMs for select group of species

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/prius-radius#3]
based on: https://github.com/inbo/fis-projecten/blob/master/Exoten/adhoc_trias_indicatoren/Scripts/Hedera_hibernica_GAM.Rmd

**Comment by bramdhondt** [comment]
@jrhillae -- Dag Jasmijn, gezien jouw beschikbaarheid (vanaf 4 juli) en het veldwerk van Sander, laat ik jou hier een doorstart maken. We kloppen onderstaande af op 5 juli.

De (eerste) drie grotere R-taken zijn **(1) verspreidingskaartjes** opmaken voor de PrIUS-soorten; **(2) de TrIAS-GAM-methode** toepassen op de PrIUS-soorten, **(3)** de problematiek kwantificeren voor **beschermde natuur**. Dit issue behandelt het **tweede**.

De soorten worden weergegeven in **Issue 2**, `data\input\prius_species_list_primary_vXX-XX-XX.csv`. Het zijn de **GBIF-codes** in dat bestand die als feitelijk vertrekpunt dienen. Het is de bedoeling dat **voor elke Nederlandstalige naam** in dat bestand **één analyse (grafiek)** wordt gelopen. Immers zijn er meerdere GBIF-codes aan eenzelfde 'soort' gebonden. Dat zijn ofwel synoniemen (bv. _Lespedeza cuneata_ en _L. juncea_) of verzamelsoorten (bv. de invasieve duizendknopen, een groep van drie soorten, bovendien elk met zijn eigen synoniem).

De **analyse** betreft het volgende: https://trias-project.github.io/indicators/ > 'Occurrence-based indicators' > 'ranking of alien taxa based on an emerging status assessment' > stap 1: **['Assessing emerging status of alien species'](https://trias-project.github.io/indicators/07_occurrence_indicators_modelling.html)**. We zijn enkel geïnteresseerd in de trend van bezette hokken (_**occupancy**_, niet _observations_). Geografisch zijn we enkel geïnteresseerd in het _Vlaamse Gewest_. Indien mogelijk, graag ook eens voor de _beschermde natuur_ (Natura-2000) apart. Als evaluatieperiode zou ik vanaf het jaar _2000_ nemen.

Als **output** willen we per soort een _grafiekje_, maar ook de waarde van de meest recente _status_. (Met de grafiekjes is er wel het probleem dat de Y-as niet van toepassing is op de GAM-resultaten. Later toe te lichten.)

**Comment by jrhillae** [comment]
@bramdhondt, @SanderDevisscher  : A short update: I overestimated my availability (workshops and finalizing business analysis)  and I was not able to start. I am back from holidays the 25th of July and then I will only focus on this for two weeks. I agreed with Sander that he will do the climate matching whereas I will do point 1 and 2.

**Comment by jrhillae** [comment]
@damianooldoni : Just out of interest: when was [the file be_classes_cube.csv]("https://raw.githubusercontent.com/trias-project/occ-cube-alien/master/data/processed/be_classes_cube.csv") updated the last time?

**Comment by bramdhondt** [comment]
@jrhillae -- In navolging van tel. comm., heb ik de output even nagekeken. Volgende opmerkingen voor de laatste loodjes.

- [ ] Er is een mapje `.\data\outpus\GAM_outputs` en mapje `.\data\output\GAM_outputs` . Graag oplossen.
- [ ] Controleer de link naar de PrIUS-soortenlijst. Bv. de laatste aanvulling, _Misgurnus bipartitus_, wordt niet binnengetrokken, terwijl die wel op de `main` staat ([prius_species_list.csv](https://github.com/inbo/prius/blob/main/data/input/prius_species_list.csv)).
- [ ] We zouden ook een tabel moeten hebben van de GAM-waarde van elke soort van het laatste jaar (2020). (0, 1, 2 of 3; resp. _not emerging_ ... _emerging_.) Te filteren uit de `.tsv`-output, en wegschrijven als apart bestandje (bv. `output_GAM_occupancy_belgium_correct_baseline_values2020.tsv`)?

Wat de "complexe soorten" betreft (Nederlandstalige soortnamen met meerdere GBIF-codes). Ik bespreek ze hieronder allemaal.

- Heel wat van deze soorten doen niet langer ter zake, want geheel afwezig uit Vlaanderen (wilgacacia, Ch. struikklaver, gest. duizendknoop, kudzu, grote vlotvaren, talgboom). Hier geen werk aan.
- De drie "complexe" rivierkreeften (gevlekte rivierkreeft, geknobbelde Amerikaanse rivierkreeft, marmerkreeft) komen éénmaal met de GBIF-aanvaarde naam voor, en éénmaal met een GBIF-aanvaard synoniem. Ik denk dat GBIF die synoniemen sowieso in rekening neemt, en er dus geen manuele lumping van de verspreidingsgegevens moet gebeuren. Maar ik zet @SanderDevisscher er hier even bij, voor de zekerheid. Los daarvan zijn er vermoedelijk te weinig waarnemingen om de GAM te laten lopen. Doe voorlopig voort zonder hier werk in te steken.
- De duizendknopen: we gaan de cijfers presenteren van Japanse duizendknoop (_Reynoutria japonica_ = _Fallopia japonica_), en de rest spreekwoordelijk archiveren. Je hoeft hier geen werk in te steken.
- Eindconclusie: geen werk aan.

Vraagje:

- [ ] Heb je er zicht op wat de procedure als een minimum aantal waarnemingen beschouwd om de GAM op te maken? Door die drempel worden heel wat relevante en vermoedelijk toenemende soorten niet behandeld. Dat vergt een bespreking in het rapport.

Ten slotte de vormgeving:

- [ ] Grafiek zonder titel.
- [ ] Grafiek zonder legende. (Die wordt eenmaal gegeven in het rapport.)
- [ ] Persoonlijk vind ik de default r-layout niet mooi. Graag het sobere maar duidelijke `+ theme_bw()`.
- [ ] De grafieken komen onder grootte 8,0 cm hoog en 10,5 cm breed in het rapport.

**Comment by jrhillae** [comment]
@bramdhondt : 
Je eerste drie opmerkingen heb ik opgelost. Zie output met emergency status van het laatste jaar voor [Vlaanderen](https://github.com/inbo/prius/blob/3_TRIAS_indicatoren/data/output/GAM_outputs/emergency_status_final_year_occupancy_flanders.csv) en [Natura2000](https://github.com/inbo/prius/blob/3_TRIAS_indicatoren/data/output/GAM_outputs/emergency_status_final_year_occupancy_pa.csv). 

Uw vraag in verband met assumpties van GAM berekening vraag ik morgen aan Damiano, wordt dus vervolgd.

De opmerkingen met lay-out heb ik niet makkelijk kunnen verwerken omdat de grafieken worden gemaakt binnen de functie [apply_gam](https://rdrr.io/github/trias-project/trias/man/apply_gam.html) die ik oproep binnen de trias package. Dit vraagt dus iets meer tijd. Ik kan de aanpassingen wel doen als ik de code van de functie kopieer binnen mijn script en binnen die code aanpassingen doe. Maar dus niet haalbaar voor mij tegen morgen.

**Comment by bramdhondt** [comment]
@SanderDevisscher @jrhillae -- FYI, ziet er goed uit.

![afbeelding](https://user-images.githubusercontent.com/78358923/186178954-b40b5082-bda9-421a-a61b-1ac35725e654.png)

Later nog wel eens kritisch bekijken. Bv. voor _Trachemys scripta_ geen output, terwijl er meer dan voldoende data is.
