### ISSUE TITLE
Scherpstellen GBIF-codes

### ISSUE THREAD

**Issue by bramdhondt** [inbo/prius-radius#34]
@fleurpet - Om een goede start te maken, is het belangrijk dat de GBIF-codes van de soorten correct zijn. Er zitten taxonomische kopbrekens tussen, dus dat is geen overbodige luxe.

De codes zoals beschreven in het PrIUS-rapport zijn hier beschikbaar: https://zenodo.org/records/7678524 . (Geen download nodig. Zenodo-datasets kunnen rechtstreeks worden ingelezen.) (Zie opmerkingen over deze codes in het PrIUS-rapport, tabellen 1 en 2, als voetnoten.) (De codes zitten ook nog in GitHub. Zie onderaan.)

In principe kunnen die codes worden overgenomen, maar ik adviseer toch even twee checks.

1. Overeenkomst met de Unielijst-GBIF-dataset van Tim _et al._: https://www.gbif.org/dataset/79d65658-526c-4c78-9d24-1870d67f8439 . Mismatches best even oplijsten, zodat we keuzes kunnen maken.
2. Nagaan of er _en cours de route_, op initiatief van GBIF, geen wijzigingen zijn gebeurd. Damiano heeft daar, dacht ik, recent een functie voor uitgeschreven.

Uiteindelijk moeten namen en codes ergens als input-bestand klaar staan, als basis voor alle verdere analyses. Voor PrIUS zag dat er zo uit: https://github.com/inbo/prius-radius/blob/main/data/input/prius_species_list.csv .

**Comment by fleurpet** [comment]
@bramdhondt

Ik heb de PrIUS-lijst zoals deze op de GitHub te vinden is (https://github.com/inbo/prius-radius/blob/main/data/input/prius_species_list.csv) nagekeken en vergeleken met de Unijlijst-GBIF-dataset van Adriaens & Oldoni (2023). 

Ter samenvatting heb ik deze vergelijking opgeslagen in de csv-file "prius_species_list_check.csv"
	
Bij vergelijking van de GBIF-codes bekom ik volgende tegenstrijdigheden: 
- de GBIF-code voor **grote waternavel** (3034613) klopt niet meer: "[Deleted on August 22, 2023](https://www.gbif.org/species/3034613). De correcte code is 7978544.
- Klopt het dat voor **waterhyacint** en **Perzische berenklauw** de synoniemen worden gegeven in de species kolom, maar dan met de GBIF_code van de ACCEPTED soortnamen?

Daarnaast bevat de Unielijst twee extra synoniemen die niet aanwezig zijn in de PrIUS-lijst, maar aangezien  dit om synoniemen gaat, maakt het voor de download in gbif geen verschil.
- voor de **Amerikaanse stierkikker**: *Rana catesbeianus* (2427092)
- Voor **fraai lampenpoetsersgras**: *Pennisetum setaceum* (2706134)

Daarnaast heb ik ook even nagekeken of de soortennamen zoals weergegeven in de "Species" kolom van de PrIUS-lijst overeenkomen met de scientific names uit de GBIF Backbone. In meeste gevallen gaat dit over kleine tekstuele verschillen (extra haakje, spatie, andere afkorting van de auteurs, ...).  
- Behalve voor **nijlgans** waar de wetenschappelijke naam lijkt te zijn aangepast van *Alopochon aegyptiacus* naar *Alopochon aegyptiaca*. De GBIF-code (2498252) bleef onveranderd.

**Comment by bramdhondt** [comment]
> Klopt het dat voor waterhyacint en Perzische berenklauw de synoniemen worden gegeven in de species kolom, maar dan met de GBIF_code van de ACCEPTED soortnamen?

@fleurpet - Ja, dat kan kloppen. Punt is dat de kolom _Species_ in dit inputbestand dichter staat bij de oorspronkelijke formulering uit de Europese wetgeving. (PrIUS-rapport, tabel 1, toont alle namen zoals die in de Uitvoeringsverordeningen zijn vermeld. Dat is in zekere zin nog steeds het ultieme vertrekpunt.)

> Behalve voor nijlgans waar de wetenschappelijke naam lijkt te zijn aangepast van Alopochon aegyptiacus naar Alopochon aegyptiaca. De GBIF-code (2498252) bleef onveranderd.

Ook een geval van de wettelijke lijst (-us) versus de nomenclatorische waarheid (-a)...

**Conclusie:** lijkt me nu allemaal wel goed te zitten. Goed dat die grote waternavel dus gecorrigeerd is.

Ter info: in de PrIUS-scripts werkte ik vaak met de Nederlandstalige namen (bij filteren, selecteren...), omdat de wetenschappelijke namen vaak zo omslachtig zijn, en codes maar codes zijn.

**Comment by bramdhondt** [comment]
@fleurpet - Deze issue/branch mag dus allicht gesloten worden. Check bij @SanderDevisscher voor een pull request, moest nog niet duidelijk zijn hoe dat moet.
