### ISSUE TITLE
Verspreidingsdata

### ISSUE THREAD

**Issue by bramdhondt** [inbo/prius-radius#35]
@fleurpet - Eenmaal GBIF-codes beschikbaar (finale, of tijdelijke), moeten we de verspreidingsdata bekomen.

Ik vrees dat we de "cube(s)" niet kunnen gebruiken (zie https://zenodo.org/records/5819028), omdat (1) de data verrasterd zijn op 1-km², wat te ruw is voor onze geografische analyses, en (2) niet al onze soorten in die lijst zitten.

We zullen het daarom met de ruwe (punt)data moeten doen. Hier zitten dus wel wat uitdagingen naar een efficiënte download, slimme data-opslag... @SanderDevisscher, volg jij dit mee op?

@fleurpet: Ik kan enkel aangeven hoe ik voor individuele soorten GBIF-downloads verwezenlijk. Zie bv. [deze voor muntjak](https://github.com/inbo/fis-projecten/blob/318_Muntjak/Exoten/muntjak/scripts/Muntjak_verspreiding.Rmd), stukje `## Dataset 1 : GBIF`. Ter inspiratie.

**Comment by SanderDevisscher** [comment]
@fleurpet je kan een lijst van soorten downloaden door in onderstaande code een lijst van taxa toe te kennen aan de parameter taxonkeys (L64).

https://github.com/inbo/vespaR/blob/a7b5f9e57a03d4529a23603411965c7e7aa31c86/Scripts/preprocessing/get_data_from_gbif.Rmd#L61-L89

Mogelijk ga je wel de soorten lijst in "behapbare" groepen moeten onderverdelen hiervoor kan je onderstaande code mits enkele aanpassingen gebruiken:
https://github.com/inbo/prius-radius/blob/75a71ca788de81026f1f32c2fb8c765cb4ea45fe/prius/r-scripts/climate_matching.Rmd#L23-L82

Denk er wel aan om de parameter `country = "Belgium"` toe te voegen aan `occ_count`. Filteren op niveau Vlaanderen is met occ_count voor zover ik weet niet mogelijk.

**Comment by bramdhondt** [comment]
@fleurpet - Ok, top!

- Aziatische boomwurger : ik zou vermoeden dat de PrIUS-waarneming [deze](https://waarnemingen.be/observation/104660699/) betreft (juli 2015). Die toont niet op GBIF (zie onder), maar moet dan kennelijk wel weer in de _cube_-dataset zitten (want ik zie niet in hoe ze anders in het PrIUS-rapport opduikt). @SanderDevisscher of @timadriaens : iemand een idee waarom die niet doorstroomt wnm.be > GBIF.org ?

![afbeelding](https://github.com/inbo/prius-radius/assets/78358923/674c170f-abdf-4456-9054-1d8345993d8d)

- Schijnambrosia : owla! Als dit de eerste waarneming is sinds opname op de Unielijst, hangt daar één en ander van verplichtingen aan vast. Die pik ik op per mail. Misschien al meteen een goede kandidaat voor het veldwerkgedeelte (noteer je hem?).

**Comment by fleurpet** [comment]
@timadriaens @bramdhondt  Het lijkt inderdaad zo dat er een filter op de waarnemingen data staat bij het overzetten naar GBIF. Het is me niet helemaal duidelijk waarop gefilterd wordt. Vind ook niet direct de repo van de wnm.be data. Iemand een idee? 

Ik kan voor twee waarnemingen in Wolvenberg en Kerkhoven eventueel even mailen Luc en Frank en informeren of deze permanent verwijderd werden.

**Comment by timadriaens** [comment]
ik denk hier https://github.com/inbo/data-publication-natuurpunt/issues maar ik vraag 't eens na bij @peterdesmet

**Comment by fleurpet** [comment]
@timadriaens Zou het kunnen dat deze repo private is? Als ik op die link klik, krijg ik "Page not found".

**Comment by peterdesmet** [comment]
Data met incidentele invoer worden [wel naar GBIF gepubliceerd](https://www.gbif.org/dataset/7f5e4129-0717-428e-876a-464fbd5d9a47#taxonomicCoverages) als deel van de Natuurpunt exoten datasets:

> The dataset contains all plant, algae and fungi taxa recorded in Flanders and the Brussels Capital Region which have the status naturalized, naturalizing, exotic, or **incidental import** in [waarnemingen.be](http://waarnemingen.be/).

Mogelijke redenen waarom https://waarnemingen.be/observation/104660699/ niet doorstroomt naar GBIF:

❌ Het taxon heeft niet een van bovenstaande statuses in waarnemingen.be. Nee, want andere waarnemingen van die soort raken er wel in: https://www.gbif.org/occurrence/search?dataset_key=7f5e4129-0717-428e-876a-464fbd5d9a47&taxon_key=3169169
❓ De waarnemer heeft niet de toestemming gegeven om data te delen
