### ISSUE TITLE
RadIUS-soortenlijst

### ISSUE THREAD

**Issue by fleurpet** [inbo/prius-radius#38]
Aanpassingen PrIUS-soortenlijst o.b.v. startoverleg RadIUS: 

**1) verwijderen niet-relevante soorten:**

- [x]  Aziatische tijgermug (*Aedes albopictus*)
- [x] alsemambrosia (*Ambrosia artemisiifolia*)

**2) uitbreiding ANB-selectie:**

- [x]  [Sika hert](https://www.gbif.org/uk/species/2440954) (*Cervus nippon*) 
- [x] [Noord-Aziatische modderkruiper](https://www.gbif.org/species/2367913) (*Misgurnus bipartitus*)
- [x] [Chinese moerasslak](https://www.gbif.org/species/9738098) (*Cipangopaludina chinensis*)
- [x] [Chinese prachtslang](https://www.gbif.org/species/9290857) ?
- [x] [wilde rijst](https://www.gbif.org/species/10919373) (*Zizania latifolia*)
 

**3) Toevoegen soorten [RIPARIAS target species list](https://www.gbif.org/dataset/fd004d9a-2ea4-4244-bb60-0df508d20a15)** 

**4) Nog te bekijken:**

- [ ]  DUNIAS: projectsoorten / alert list
- [x] rivierkreeften

**Comment by fleurpet** [comment]
```{r get-wfshab}
wfs_bwk <- "https://geo.api.vlaanderen.be/BWK/wfs"

url <- parse_url(wfs_bwk)
url$query <- list(service = "wfs",
                  version = "2.0.0", # facultative
                  request = "GetFeature",
                  typename = "BWK:Bwkhab")
request <- build_url(url)
request

bwkhab <- read_sf(request) %>%
  st_transform("+proj=longlat +datum=WGS84") %>%  
  ensure_multipolygons()   
```

```{r leaflet-bwkhab}
leaflet() %>% 
  addTiles(group = "OSM") %>%
  addPolygons(data = bwkhab, color = "purple")
```

**Comment by timadriaens** [comment]
Toplijstje. 'T moet wel Noord-Aziatische modderkruiper zijn.

**Comment by fleurpet** [comment]
Ai, verstrooidheidsfoutje.. 

@timadriaens @bramdhondt - Tijdens het startoverleg haalde Nicolas ook even de prachtslang aan. Gaat dat over deze soort: https://www.gbif.org/species/8889878? Voeg ik deze ook toe aan de RadIUS soortenlijst?

**Comment by fleurpet** [comment]
Van de 30 soorten in de RIPARIAS alert lijst, heb ik onderstaande 11 soorten toegevoegd aan de RadIUS lijst. (De overige 19 soorten waren al aanwezig in de PrIUS lijst):

| Groep |Scientific name | Soort | Lijst | GBIF key |
| ------- | ---------------- | -------- | ----- | ----------|
 dier | *Faxonius juvenilis* | Kentuckyrivierkreeft | RIPARIAS | 8721209
 dier | *Faxonius immunis* | Calicotrivierkreeft | RIPARIAS | 8930656
 dier | *Procambarus acutus* | Gestreepte Amerikaanse rivierkreeft | RIPARIAS | 2227289
 dier | *Cherax destructor* | Gewone yabby | RIPARIAS | 4417558
 plant | *Houttuynia cordata* | Moerasanemoon | RIPARIAS | 5384931
 plant | *Aponogeton distachyos* | Kaapse waterlelie | RIPARIAS | 5328593
 __plant__ | __*Egeria densa*__ | __Egeria__ | __RIPARIAS__ | __5329260__
 plant | *Pontederia cordata* | Moerashyacint | RIPARIAS | 2766030
 plant | *Petasites japonicus* | Japans hoefblad | RIPARIAS | 3088310
 plant | *Saururus cernuus* | Leidse plant | RIPARIAS | 5384932
 plant | *Erythranthe guttata* | Gele maskerbloem | RIPARIAS | 7346102

Al deze GBIF keys lijken te kloppen, behalve die voor Egeria: [*Egeria densa*](https://www.gbif.org/species/5329260) (5329260) is een synoniem voor [*Elodea densa*](https://www.gbif.org/species/5329263) (5329263). Gebruik ik de GBIF key voor *Elodea densa*?

**Comment by timadriaens** [comment]
yep, Elaphe taeniura. Je leest er meer over [hier](https://doi.org/10.3391/bir.2021.10.3.24).

**Comment by timadriaens** [comment]
wrt Egeria, indeed, best to use [this one](https://www.gbif.org/species/5329263), Egeria densa is considered a synonym

**Comment by bramdhondt** [comment]
@fleurpet - Wat **DUNIAS** betreft:

- Het rapport vind je hier: https://pureportal.inbo.be/en/publications/assessment-of-current-and-future-invasive-plants-in-protected-dun .
- Ik zou de volgende projectsoorten (niet-alert-list-soorten) sowieso toevoegen (sommigen reeds op lijst):
_-- Ailanthus altissima
-- Baccharis halimifolia
-- Berberis aquifolium
-- Lycium barbarum
-- Rosa rugosa
-- Elaeagnus angustifolia
-- Symphoricarpos albus
-- Parthenocissus quinquefolia
-- Parthenocissus inserta_
-- @timadriaens : enige niet opgenomen is _Cotoneaster_ spp. Ik zou voorstellen daar even rond te fietsen. 
- De alert-list-soorten voor België staan op pdf-p. 46. @timadriaens : in _hindsight_, is dit wel zinvol? Het gaat om uiterst zeldzame, en momenteel vooral afwezige soorten (< 10 waarnemingen sinds 1950). Mee doorgaan?

**Comment by bramdhondt** [comment]
@fleurpet - Wat de **rivierkreeften** betreft:

Ik zou eens contact opnemen met Kevin Scheers en Frédérique Steen, hen uitleggen waar je mee bezig bent, en de reeds opgelijste rivierkreeften voorleggen. Afh. van hun werk / afspraken met ANB, kunnen ze dan misschien nog soorten toevoegen.

**Comment by bramdhondt** [comment]
@fleurpet - Ik zag je _commit_ en vragen daarbij.

Wat _Lijst_ betreft, heb ik me het volgende bedacht, voor soorten die op meerdere lijsten staan (bv. _Crassula_: ANB-lijst, RIPARIAS-lijst; _Heracleum_: EU-lijst, RIPARIAS-lijst; _Baccharis_: EU-lijst, DUNIAS-lijst...): in plaats van daar een prioriteit aan te geven (bv. RIPARIAS > ANB), kunnen we ze meer recht doen door de EU-lijst, de RIPARIAS-lijst en de DUNIAS-lijst als aparte variabelen te beschouwen (EU-lijst: waarden 1-4; RIPARIAS-lijst: 1/0; DUNIAS-lijst: 1/0). De ANB-lijst mag dan gewoon de restgroep zijn ('1' voor alle soorten waar de vorige waarden '0' zijn). Op die manier zullen we ook vlotter binnen het RIPARIAS- en DUNIAS-project kunnen uitpakken met ons werk.

Excuses voor deze late bedenking.

Daarnaast zitten er voor sommige soorten meerdere taxa / GBIF-codes in de soortenlijst. Ik weet dat dat bij PrIUS ook zo was, maar wat mij betreft mag je gerust voor één taxon / GBIF-code gaan _in de gevallen waar GBIF de taxa als valide synoniemen beschouwd_ -moest je dat handiger vinden. Ik vermoed dat dat voor alle gevallen zo is, uitgenomen drie van de zes 'invasieve duizendknopen', waar het echt om een lumping van verschillende taxa gaat.

![afbeelding](https://github.com/inbo/prius-radius/assets/78358923/a54ef8c9-0c13-4e5b-95bb-9b1703c06218)

**Comment by fleurpet** [comment]
@bramdhondt Ik heb de RadIUS lijst aangepast o.b.v. je voorgaande comment. Nu staan er 4 extra kolommen (EU_lijst, RIPARIAS_lijst, DUNIAS_lijst, ANB_lijst) die telkens aangeven in welke lijst(en) een soort voorkomt. Ook de synoniemen werden uit de lijst gehaald. 

De enige bedenking die ik me nu nog maak is dat er voor de soorten die werden toegevoegd uit de RIPARIAS-lijst momenteel in de kolom 'Species' de scientific name staat zoals in de oorspronkelijke alert list. Is het beter om hier de GBIF scientific name te zetten (incl. auteur, jaar, ...)? 

vb. 
![image](https://github.com/inbo/prius-radius/assets/117445190/3c233d3c-5429-421a-89ca-b1648888deb9)

**Comment by timadriaens** [comment]
yep, je hebt gelijk. Inderdaad, ziet er goed uit dus, ik zat met het recente geval Amerikaanse nerts in mijn gedachten (taxon Neogale vison bestaat niet op gbif dus iNaturalist data is gewoon niet gemapt) maar dat is dus een andere case die zich hier niet stelt (tenzij amerikaanse nerts ook wordt beschouwd?). Ook Rana catesbeiana is mee wellicht voor `247091`?

**Comment by fleurpet** [comment]
@timadriaens amerikaanse nerts staat momenteel ook in de soortenlijst onder de ANB-selectie met de GBIF key [5218823](https://www.gbif.org/species/5218823). Maar dit klopt dan niet? 

*Rana catesbeiana* zou ook in de download moeten zitten onder *Lithobates catesbeianus*. Dat deze niet in bovenstaand overzicht staat kan eventueel zijn omdat er van dit synoniem in Vlaanderen nog geen observaties op GBIF staan. Zou dit kunnen?

**Comment by timadriaens** [comment]
jawel, dat klopt zeker, maar zoals je zal zien in de dataset overview, zitten er geen records van iNaturalist bij, doordat iNaturalist de nieuwe naam Neogale gebruikt (op het spoor gekomen bij de uitwerking van de SDM horende bij de PRA voor Europa). Even gecheckt, de enige records is [deze](https://www.inaturalist.org/observations/5013611). En die zit ook in waarnemingen dus je mag ervan uitgaan dat alles ok is.

**Comment by fleurpet** [comment]
@bramdhondt @SanderDevisscher 

Ik heb alle aanpassingen/toevoegingen voor de RadIUS-soortenlijst doorgevoerd. 

Alle aanpassingen gebeuren in het script [preparing_radius_species_list.Rmd](https://github.com/inbo/prius-radius/blob/aanpassingen-species-list/radius/r-scripts/preparing_radius_species_list.Rmd). Waarin ik o.b.v. de PrIUS-soortenlijst volgende stappen volg:
1. Vergelijken GBIF keys met Union list dataset (Adriaens & Oldoni, 2023) (zie #34)
2. Aanpassingen ANB soortenselectie
3. Inladen RIPARIAS alert list 
4. Toevoegen DUNIAS project species 
5. Combineer soortenlijsten
6. Verifieer GBIF keys tegen de GBIF Backbone
7. Aanpassingen RadIUS-lijst voor export

De resulterende soortenlijst staat [hier](https://github.com/inbo/prius-radius/blob/aanpassingen-species-list/radius/data/input/radius_species_list.csv). 

Zijn er nog opmerkingen of suggesties? Zo niet, kan ik eventueel overgaan op een pull request en deze eerste versie van de soortenlijst voorleggen aan Nicolas.

**Comment by bramdhondt** [comment]
@fleurpet - Ok, geen verdere opmerkingen.
